
name: Autograding

on:
  push:
    paths:
      - 'src/main/java/**'
  pull_request:
    paths:
      - 'src/main/java/**'

jobs:
  car_tests:
    name: Car Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Gradle
      run: ./gradlew build
    - name: Run CarTest
      run: ./gradlew test --tests "com.example.CarTest"

  rectangle_tests:
    name: Rectangle Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Gradle
      run: ./gradlew build
    - name: Run RectangleTest
      run: ./gradlew test --tests "com.example.RectangleTest"

  # Similar blocks for other classes...

